# Generated by Django 5.0.4 on 2024-05-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_admin_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToCart',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
