# Generated by Django 5.0.4 on 2024-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useruid', models.CharField(default='0000', max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('productimage', models.ImageField(default='abc.jpg', upload_to='')),
                ('productid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useruid', models.CharField(default='0000', max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('productimage', models.ImageField(default='abc.jpg', upload_to='')),
                ('productid', models.CharField(max_length=255)),
            ],
        ),
    ]
