# Generated by Django 5.0.4 on 2024-05-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='productimage',
        ),
    ]
