# Generated by Django 5.0 on 2024-05-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='prodid',
        ),
    ]
